-- ⚠️ DEPRECATED — 사용 금지 (DO NOT RUN) ⚠️
--
-- 이 파일에 있던 구버전 sp_SaveWorkout(10-param) 정의는 제거되었습니다.
-- 구버전은 다음 문제로 데이터를 유실합니다:
--   1) DS 를 exercise_type='dynamic' 일 때만 저장 → 웹앱이 보내는 'DS' 와 불일치하여 DS 누락
--   2) workout_exercises/workout_history_detail 에 reps 컬럼을 INSERT 하지 않아 reps=0 저장
--
-- 정식(최신) 정의는 아래 파일입니다 (19-param: reps + DS/CD 정상 저장):
--   packages/api-server/database/sp_save_workout_with_reps.sql
--
-- 적용 방법:
--   mysql -u root -p workout_system < database/sp_save_workout_with_reps.sql
--
-- 이 파일을 실수로 실행해도 더 이상 구버전 프로시저가 배포되지 않도록 정의를 비워 둡니다.
